### PR TITLE
Fix sortable() is not a function if include only sortable.js

### PR DESCRIPTION
**Pull request by pxpm**
Can anyone confirm this? If yes, i have applied this fix and it's working.

If included only sortable.js i got the following error on console:

```
Uncaught TypeError: Cannot read property 'mouse' of undefined
    at sortable.js:28
    at sortable.js:24
    at sortable.js:26
jquery.min.js:2 jQuery.Deferred exception: $(...).sortable is not a function TypeError: $(...).sortable is not a function
    at HTMLDocument.<anonymous> 
jquery.min.js:2 Uncaught TypeError: $(...).sortable is not a function
    at HTMLDocument.<anonymous> (edit:977)
    at l (jquery.min.js:2)
    at c (jquery.min.js:2)
```

If i include whole jquery-ui as in the fix, the error is gone and the field it's working.

Thanks

### CODE REVIEW

**Comment by evanrthompson** [comment]
Seeing the same issue and the same fix works for me locally.

**Comment by stevecrossuk** [comment]
I've just found this error on my latest Backpack application :-) Will this update fix work on CRUD 3.5?

**Comment by pxpm** [comment]
@stevecrossuk yes, i think this only got merged on 3.6... maybe @tabacitu can create a minor update on 3.5 for people who still using it to benefit from it, but with v4 upcoming it think it's not going to happen!
