### ISSUE TITLE
[Bug] field 'name' calls parent model method

### ISSUE THREAD

**Issue by MikeyBeLike** [Laravel-Backpack/CRUD#3513]
# Bug report

This is a bug I discovered after upgrading to 4.1

### What I did
My normal crud controller prior to 4.1 has a field called increment.
e.g 
```php
$fields = [
...
            [
                'name' => 'increment',
                'label' => 'Increment',
                'type' => 'number'
            ],
...
];
$this->crud->addFields($fields);

```

### What I expected to happen

No errors to occur and my fields displayed

### What happened

Received an error:

> Too few arguments to function Illuminate\Database\Eloquent\Model::increment(), 0 passed in /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1878 and at least 1 expected

### What I've already tried to fix it

Upgrading to 4.1 I see this message on the docs:
![image](https://user-images.githubusercontent.com/1624261/106771520-f46d4100-6636-11eb-8d26-5ced88bb8c1a.png)

So which lead me to believe that it was trying to access a relationship/method on the model instance, since `increment()` is a method on the `Model` parent class it tried to trigger that - even though it is not a relationship.

I fixed it just by doing this:
```diff
            [
                'name' => 'increment',
                'label' => 'Increment',
+               'entity' => false,
                'type' => 'number'
            ],
...
];
$this->crud->addFields($fields);

```

Not an issue.. but think it would be good to continue to display the field if it is a non-relation as it does now. It took me 2 seconds to figure it out as i've gone through the updated docs and read about it, but for others could be an idea to just have this documentated somewhere.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.7 (cli) (built: Jun 12 2020 00:04:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.25.0@05da44d6823c2923597519ac10151f5827a24f80

### BACKPACK VERSION:
4.1.31@e0c389acce2617099a69d0b6076dfad24385295f

**Comment by pxpm** [comment]
Hello @MikeyBeLike 

Thanks for the report. We have that notice in the main `Fields` page. I'v submitted a PR: https://github.com/Laravel-Backpack/docs/pull/234 to add it to the columns page too.

We plan to refactor this bit, and will solely depend on `return types` from the functions. At the moment we support PHP versions that don't support return types. 

When that time comes, it should be easy to just add the return types to your relations and everything inside backpack (from user perpective) will work the same. 

I am closing this for now, If you have other suggestions where that notice might be usefull, please let us know. 

Best,
Pedro
