### ISSUE TITLE
[BUG] datepicker field gives js error $(...).datepicker not defined

### ISSUE THREAD

**Issue by dobromir-hristov** [Laravel-Backpack/CRUD#449]
As the title says it, I get this `$(...).datepicker not defined` error, but I have published all the configs and should have the vendors and everything. 
The datepicker.js script is loaded as well.
Laravel 5.4, with latest versions of Base/Cruds etc.

**Comment by adbmdp** [comment]
Same bug for me.

**Comment by gilbertsmink** [comment]
was just about to post this

**Comment by KevinRignault** [comment]
I also have this bug !

**Comment by OwenMelbz** [comment]
Curious to know if it was caused maybe by this PR? https://github.com/Laravel-Backpack/CRUD/pull/408/commits/987f2d5644c851486387b2a21e8613271301cfa8

If you guys could reverse the change made in that commit, and see if it fixes it, then we know the culprit

**Comment by KevinRignault** [comment]
Hi @OwenMelbz, thanks for you answer. 
I reversed those changes, and I just have a little JS error : invalid date.
But the datepicker works fine !

**Comment by KevinRignault** [comment]
Hi @OwenMelbz,
Thanks for your answer.
I made those changes and also tested your last fix. 
The datepicker works fine but if I have an address field (with the autocomplete), this field doesn't works anymore.

**Comment by mariavilaro** [comment]
Same problem here, and yes if I revert #408 it works

**Comment by jhivan** [comment]
I have a similar issue. 'date' type works fine but when i use 'date_picker' (even when copy pasted from docs) chrome and firefox throws this error:

`TypeError: $(...).datepicker is not a function[Learn More]`

**Comment by MarcosBL** [comment]
Have you tried this ? https://github.com/Laravel-Backpack/CRUD/pull/159#issuecomment-282491621

**Comment by Athuli7** [comment]
I had mentioned this error as PR in the Base Repo.
https://github.com/Laravel-Backpack/Base/pull/110
jQuery ui is not loaded.

**Comment by skatika** [comment]
Adding the jquery ui fixed it for me.

**Comment by Athuli7** [comment]
@skatika, yes. But it needs to be a part of the Base. And I've made the PR. But no response.

**Comment by pavoltanuska** [comment]
Well, this goes a little deeper.

First of all, the absence of jQuery UI __is not__ the real issue here.

This all comes down to a [bug in Bootstrap Datepicker](https://github.com/uxsolutions/bootstrap-datepicker/issues/736) which has been [fixed since Oct 14, 2014](https://github.com/uxsolutions/bootstrap-datepicker/commit/f5c9849491c8a0aaa09477eb87e747a00c37f19e#diff-dd513a8bab7ad1033c8784c4a1b9ce15L1668).

As Backpack depends on AdminLTE (and its plugins) and AdminLTE uses outdated version of the Bootstrap Datepicker (issue already opened - https://github.com/almasaeed2010/AdminLTE/issues/1462) we're stuck with the buggy version right now.

I'm definitely __against__ including jQuery UI as a fix for this issue, since it's not the right solution.

The question is, how to fix it?

@OwenMelbz @tabacitu - what's your strategy for stuff like this (outdated packages in dependencies)? Should we add our own separate version of said package (Bootstrap Datepicker in this case) and use that one, or should we wait for fix in AdminLTE and use some kind of workaround for now?

As for the workaround (or call it a hot-fix), the best I came up with is to change the #408 to:
```
if (jQuery.ui) {
    var datepicker = $.fn.datepicker.noConflict();
    $.fn.bootstrapDP = datepicker;
} else {
    $.fn.bootstrapDP = $.fn.datepicker;
}
```
It isn't ideal, since jQuery UI is not necessarily the only package causing conflicts here, but it's the only one that we know of right now.

**Comment by tabacitu** [comment]
@pavoltanuska , I love your reply, and I completely agree with your temporary fix. Would merge it right away if you can submit a PR.

I can't say I have "a strategy" for outdated packages in dependencies, but:
- when laracasts/generators didn't update to L5.4 for weeks, I submitted a PR;
- when prologue/alerts didn't support new Laravel versions, I took over maintaining it;
- if AdminLTE doesn't update their dependencies for a while, I think we (the Backpack community) should totally help them out with PRs; I see you've already submitted an issue, kudos to you!
- in this particular case, since we have a working fix (yours), and from what I can tell, it will be backwards-compatible when we update, I say let's include this fix into our datepicker field;

Cheers!

**Comment by pavoltanuska** [comment]
Alright, thanks for the insights and of course for all the work done @tabacitu !

I'll keep an eye on the AdminLTE's take on this issue and will let you guys know once it's fixed.

**Comment by tabacitu** [comment]
That would be great, thank you! 

Just merged your PR, so let's close this bad boy. Cheers!

**Comment by kanyapila-101** [comment]
I can not used datetimepicker on mac os Is I used Modal BS. datetimepicker display background modal
Help Me.

**Comment by lloy0076** [comment]
@kanyapila-101 - at the very minimum we'd need to know if your debug console showed any errors (especially missing files, actual error logs and so forth) and a basic idea of your setup.

As it's not obviously related to this issue, it might be best to open another issue and start there.

If it relates to __this__ issue we can always reference it back to here later.
